[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    ;=========================================
    ; TFT Driver
    ;=========================================
    -D USER_SETUP_LOADED
    -D ILI9488_DRIVER

    ;=========================================
    ; Hardware SPI
    ;=========================================
    -D TFT_MOSI=23
    -D TFT_MISO=19
    -D TFT_SCLK=18
    -D TFT_CS=27
    -D TFT_DC=32
    -D TFT_RST=33

    ;=========================================
    ; SPI Speed
    ;=========================================
    -D SPI_FREQUENCY=20000000
    -D SPI_READ_FREQUENCY=10000000

    ;=========================================
    ; Fonts
    ;=========================================
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D LOAD_GFXFF

    ;=========================================
    ; PNG logo buffer
    ;=========================================
    -D PNG_MAX_BUFFERED_PIXELS=400

    ;=========================================
    ; Touch Disabled
    ;=========================================
    -D TOUCH_CS=-1

board_build.filesystem = littlefs

lib_deps =
    bodmer/TFT_eSPI
    waspinator/AccelStepper
    bitbank2/PNGdec

build_unflags =
    -Os
