#include "logo.h"
#include <Arduino.h>
#include <TFT_eSPI.h>

const int16_t LOGO_SOURCE_W = 240;
const int16_t LOGO_SOURCE_H = 157;

// Compact RLE of a 4-bit anti-aliased monochrome version of the user's
// converted 398x260 RGB565 logo. It is decoded once into a small RAM buffer.
static const char logoEncoded[] PROGMEM =
    "AQEBBXIAAQMCAgEEAQABAQEEAQEBBAEC5QABAQEHAQABAQEDAQABCAEHAQPKAAEBAQARAQIAAgEIAAIBAgABAQEAAQEBAgIAAQIBAQUCAQEBAAcBAQABAbUAAQUBAwEIAgUIAwEGAQcBBgEHAQYBBQIBAQYBBAMAAwEBAAEEAgIDAQQAAQIBCQELAwkBCAEJAQcIAwECAQYBBwEEAQIBAAEEsQABAgEBEgABAQEABgEBAAEEAQMBAgYBAQABAQEAAQIQAAECAQMBAgEAAgOvAAEBAgAaAQIAAQUBBwEACAEBABABBQABBQECAQOsAB4BAQABBQEIAQYBAB4BAQABBQEEqwACAQIA",
    "GwEBAAEGAQkBBgEAGwEBAAMBAQABAQECqAAhAQEAAQYBCQEGAQAhAQEAAQIBAaMAAgEBAAUBAQATAQIABgEBAAEEAQgBBgEACAEBABcBAQABAgEFpAAGAQIAAQEBAAEBAQAJAQMAAQECAAkBAQABAQIGAQAGAQEAAQEBAwEAFwEBAAEEAQKlAAMBAQABAgEEAwEBBQkAAQEBCAEBAwABCAEBAQAGAQEAAQECBgEABgEBAAEDAQUUAAYBpQACAQMAAgEBBAEDAQABAgoAAQMEAAEBAgAGAQEAAQECBgEABwEBBRkAAQEBAAEBAQKhAAEBAQICAAICGAAHAQEAAQEBBgEHAQAIARcAAQEBAwEBAQABBAEGpAABARsABgEBAAEEAQYBBAEABgEBAAEFAQEXAAIBpgABBAEBGwAGAQEAAQcBBQEBAQAGAQEAAQUBARoAAQMBBKMAAQMBARsABgEBAAEHAQYBAQEABgHfAAYBAQABAwEEAQIBAAYB3wAGAQUABgHfAAYBAgABAwEEAQAFAeAABwEBAAEFAQcBAAUB4AAHAQEAAQQBBgEABQHgAAcBAQABBAEHAQAFAeAABwEBAAEEAQcBAAUB4AAGAQIAAgEBAAYB3wAGAQUABgHfAAYBBQAFAeAABgEFAAYB3wAGAQUABgHfAAYBAQABAwECAgAFAeAABgEBAAEEAQUBAwEABQHgAAYBAQABAwEFAQQBAAUB4AAGAQIAAQMBBQEABQHdAAEBAQIBAAYBBQAGAdwAAQEBBAEABgEBAAEBAwADAQEAAgHeAAYBAQABAQEFAQABBAEBAQAFAdwAAQEBAgEABQEEAAEDBwHfAAUBBwAHAd0ABQEBAAEBBAAFAQEAAQMBBNwABQEBAAEBAQIEAAYBAQABAQEF2QABAQEEAQAEAQgAAwEBAAMB2wABAQEABQEHAAYB2wABAgIABAEHAAEBAQAEAQEAAgHZAAEEAQEBAAUBBQACAQEABAEBAAEBAQPYAAECAQEBAAUBCAAGAQEAAgHXAAECAQMBAAQBAQABAgEBBQACAgEABgHYAAcBAQABAwECBQABAgYBAQACAdkABAEBAAEBAQIGAAECAQQBAAQBAQACAdYAAgEBAAQBAQABAQEDCQACAQEAAgHYAAEEAQMBAAUBDAACAQEAAQHaAAUBCgABBQEBAQACAQEAAgHWAAEFAQICAAQBDQACAQEAAgHVAAEDAQQBAgEABgENAAQB1QABAQEFAQAEAQ8AAQEBAAQB1wAFAQ0AAQEBAwEABQEBAtIAAQECAAQBDgABAgEFAQAEAdMAAQIBAQEABAERAAEBAQAEAQEAAQPQAAEDAQIBAAMBAQABARAAAQUBAwEAAwEBAAEEzwABAQIABAEBAAIBDwABAgEBAQAEAc8AAgEBAAQBAQABAgEBEgABAQEABAEBAAIDywACAQEABAEBAAEEAQIRAAEDAQUBAAQBzQABAwEBAQAEAQIAAQMBAhIAAgEBAAQBywABAQEEAgEBAAIBGwADAQEAAQIBBccAAQEBAgEDAQADAQEAAQUBAhcABgEDAAEByAABAQEAAQECAAEBGAABBQEEAQEBAAIBAwABBcIAAQIBAwEBAQAEASEAAwEBAAEBAQQBAsAAAQIBBAQBJQABAQEAAQEBBwEGAQG9AAEBAQICAAMBAQABAwECIQACAgEAAQECAAIBvQACAgMBAwABAQECIQABAgEEAQIBAAMBAQABAbsAAQEBAgQAAQMBAgEEAQEjAAEBAQUDAAEBAQACAboAAgMEAAQBJgABAQED7gABAQEEAQABAv8AxgABAQEDAQQBAuoAAQIBAAEBAQMBBAEIAQfpAAEEAQcEAAECAQQBA+gAAQIFAQEAAQblAAEBAQABAQEABQEBAAEEAQgBAeMAAQEBAAgBAQABBQEC4wABAQEDCAHmAAICAQAJAeUAAQEBAAcBAQACAeQAAQEBAAgBAQcBA+QAAQECAAUBAQABAQED5QABBAEBAgACAQIAAQHnAAEBAQUBBAEHAQEBAAEB
    "AQABAuoAAQMBAQEAAQGXAAEBAQMBAQEDAQQBBrcAAgEWAAECAQkBAwIAAQMOCQEHAQEBCQEBAQgBBwEDAQEBAwEAAgIBA7UAAQICAAEBAQACARAAAgIDAQEEFQABAwEEAQIEAAEGtQACAwEAAgEBAAIBAQQBAg0AAQEBBQQBAQAVAQMAAQEBAAIDAQUBAhoAAgFPAAECGwABBAEBKwAGAQIAAQIBAQ0AAQMDAQEAGgEBAAEBAgIaAAEBDQABAQEEAQABAQEDOQABAQEAAQEIAAEFAQEWAAECAQERAAEDGgACAQEAAQEBAAEBAQABAQ4AAQUBABEBAwABAQEABQEBAAMBHAACAQ8AAQEBAyMAAQUUAAEGCgEEAAECEwABAQUAAQIBBAwAAQQFAAIBDgADAQEAAQEBAAEBAgADAQ8AAQMBAAEBAgACAQ0AAgEBAAEBAgAEAQEAAQEqAAECAQACAQEAAQESAAEEAwEBAAECAQMKAAEBAQAEAQ8AAQIDAAEBBAAFAQEAAQETAAEFAQEBAAIBAQABAgEEDgAFAQ4AAQECAAIBAQABBQECBAABAQEAAQEOAAIBAQABBA4AAQEBBAEKAQQBAAUBAQACAR4AAQELAAEDAQQBAAMBAQMRAAECAQEBAAEBAQACAgwABAEOAAEBAQAEAQICAQQBBQEBAwACARQAAQIBAAMBAQACAg0ABQEPAAECAQEBAAIBAQABAwEBAgABAgEBAQADASEAAQEBBQEBAQACAQMAAQIeAAIBDgABAQIAAQQSAAEBAQABAQ4ABAEBAAEFDQAEAQIAAQQBAQcAAwECAAIBDwAFARAAAwEBAAIBDAABAQEABAEFAAEDAgQBAAMBIAABCAEEAQAFAR8AAQEBAAEBDQAEARIAAQUDAQ8AAwEBAAEBCwABAQEAAwEJAAEBAwADAQEAAgEQAAQBEAADAQEAAgELAAEBAQUBAAIBCQABAQEABAECAAECAQMaAAEBAQIBAAYBGwABAQECBQEOAAIBAQABAQECEgACAQ8AAwEMAAEBAQIBAAMBDgACAQEAAQEBAAEBDwACAQEAAQEQAAMBAQACAQ0AAgEOAAMBAQABAQECGgABAQEABwEbAAIDAQABAQEAAgENAAQBAQABBAECEAADAQ8AAwEMAAEDAQIBAAIBAQACAQ0AAgECAAEBDwACAQEAAQEQAAQBDAAFAQEAAQUKAAIBAQADAR4ABwEZAAEBAQMCAAUBDQABAQEAAgEBAAECAQUQAAMBDwADAQ0AAQEBAAMBEAACAREAAgEBAAEBEAAEAQ0AAQEBAAIBAQIBAQsAAQIFARsAAQIBAQEABgEZAAEBAQIBAAYBDgAEARMAAgEPAAMBCwABAQEFAQAEAQ4AAQIBAxMAAgEBAAEBEAAEAQsAAQEBAAIBAQABAQEFDAABAgEDAQADAQEAAQEZAAEDAQIBAAUBAQABBAECFQABAQEFAgAHAQ0AAgECAAIBEgACAQ8AAwEOAAEBAQACAQ4AAQMBAgIAAQIQAAQBEAAEAQ0AAgEPAAEBAQQBAAQBGwABAQEABwEWAAECAQMCAAMBAgACAQ0ABgESAAIBDQABAwEAAwEOAAUBIQAFARAABAEMAAEBAQABAQEAAQQBAQ4AAQEBAAQBGAABAQEGAQIBAAUBFgACAQEABgEBAgEAAwEMAAcBAQABAQ8AAgENAAEIAQADAQ0AAQUCAAUBAQABAQECHAAFARAABAEKAAEFAQIBAAIBAQABAgEBDgACAQIAAgEBAAECAQUBARQAAQEBBAEABgEXAAEBAQAGAQEDAQACAQ0ACAEBAAEFAQMNAAIBDwADAQ0ACgEdAAUBEAAEAQsABAEBAAEEAQEPAAIBAQADAQEAAgIXAAYBGAAFAQEAAQIBBAEAAgENAAMBAgADAQEAAQEBAg0AAgEPAAMBDgABBQECAQAEAQEAAQEdAAUBEAAEAQoABQEBAAEGAQISAAYBAQMWAAYBFAABAwECAQAFAQMAAQMBAAIBDQACAQEABAEBAAEBDgADAQ0AAQcBAAQBDgACAQEABwEFAAECFQAFARAABAELAAEBFgABBAEDAQADAQEAAQQBBxMAAQIBBAEABQEUAAEBAQUBAQEABAEFAAMBDQACAQEAAQcBBQEAAgEBAAIBDQACAQ0AAQoBAAQBDgACAQEACgEYAAUBEAAEAQsAAQEYAAQBAgABAhMAAQEBAgEABAEBAAEBEQABAQECAQEBAAIBAQACAQcAAgENAAUBAQAGAQIAAQIJAAIBDQABCQEABAEUAAgBFwAFARAABAEMAAMBFAABAQEAAgEBAAMBFQAGARIAAQICAAUBBwADAQ0AAwECAAEDAgAEAQwAAgENAAEJAQAEAREAAQIBAAEBAgAJAQQAAQIPAAUBEAAEAQwAAwETAAIBAQAFARYABgEQAAEBAQIBAQEABQEBAAIDBQADAQ0AAwEBAAEDAgYBAAYBCgACAQ0AAQkBAAQBEwACAgIACQEDAAEGDwAFARAABAEMAAMBEwABBAECAQAFARYABQEBAAEBDQACAgIBAQAEAQMAAgEFAAMBDQADAQIAAQMBCAgBAwABAgQAAwENAAEJAQAEARQAAQEEAAkBEQAFAQ8AAQEBAAMBDAADAQEAAQUBARMABQEWAAYBDgACAgEACAEJAAIBDQACAQUAAgEBAAYBAgABBQECBAACAQ0AAQkBAAQBHAAIAQEAAQQBAwEBCwAFAQ8ABQENAAIBAgABARMABQEXAAQBAQACAwwAAQQBAgEABAECAAEBCgACAQ0AAwEFAAEBAQUBAAYBAQACAwECAQQBAAMBDQABCQEABAEeAAgBAQMBBAsABQEPAAUBCwAEAQEAAQQBBRIAAQEBAAQBAQIWAAQBAQACAQoAAwEBAgYBCwADAQ0AAwEGAAECAgEBAAMBAQABAQIAAQIBCgEAAwENAAEJAQAEARwAAQMBAgUBAQACAQ0ABQEPAAUBCwAEAQEAAQIRAAECAQEBAAIBAQABAQEAAQEVAAQBAQABAQwAAgEBAAUBAQABAQsAAwENAAIBCQABAQIABQECAAEDAgACAQ0AAQoBAAQBHAABAwEBAQAIAQIAAQIJAAUBDQABAQEABQELAAUBEgACAgEABQEWAAQBEAADAQEAAQEMAAEEAQIBAAIBDQADAQgAAQQBAQEABgECAAECAgABAQ0AAQUBAAQBHQABAgEDAQAIAQEAAQUKAAQBDAABAQEFAQAFAQwABAEBAAEBDwABAQEDAQAFAQEAAQIVAAYBAQkKAAIBAQAEAQ0AAQIBAAMBDQACAQkAAQIBAQECAQQBAAQBAgACAQEAAQENAAEHAQAEAR0AAgEDAAYBAgABAgkABgEEAAQBAQABAQMABQEMAAQBAQABBAEDDwABAQEABQEBAAEFFAAHAQEECAACAQEABQEBAAECAQEMAAEFAQACAQ0AAgENAAYBAQABBQEBAQABAQwAAQEBBgEABAEkAAUBCwAJAQEABQEBAAgBCwAGAQIAAQENAAEDAgAEAQEAAQIWAAUBCgABAgEEAQAGAQEAAQQBAQEABAIEBwEGAQEBAgEAAgENAAIBDAACAgEBAQABAQEAAwEBAAIBDAABBAEHAQAEAQkAAQEBAgEBAQIBBBYABQEBAAEEAQEIAAcBCAADAQIABAEKAAEBAQQBAAQBAQABAgEEDQABBQEBAQAEAQEAAQUBARQABgEJAAIBAgAGAQQABAEFBAEAAQEBAAIBDQACAQ0AAQECBAEAAwECAAIBDAABBAEHAQAEAQwAAQEBAxYABQEBAAEEAQcIAAQBAQABBQECAwAFAQICAQMBAQEABQEKAAEEAQIGAQECDwABAQEAAgECAAEBEwACAwEABQELAAcBAQAEAQkABQENAAIBDgABAQEDAQEBAAYBDwAEAQsAAQECAAIDFAAFAQIAAQIHAAUBAQABBAEDDQAGAQkAAQIBAwEABQEQAAQBAQABBAECEwACAQEABQEJAAIBAQAEAQMAAQEBAAkBAQABAQIAAQEBAAEBDQACAQ8AAQYBAwIAAQEBAAMBDwAEAQsAAgEBAAIBEgABAQIABAEKAAUBAQACAQwABwENAAEBAQACAQIAAgEMAAQBAQABAhYABQEBAAECAQEHAAIBAQAFAQ0AAQIBAAIFAQACAQ0AAgEQAAEBAgAFAQ8ABAEKAAQBFQABAwEABAEBAAEFAQEHAAYBDwAGAQsAAQEBAAMBAQABAQEAAQYBAQoAAgEBAAEBGAACAwEABQEIAAIBAQAEAQEAAQENAAEEAQABCAEBAQACAQ0AAgERAAEBAgAEAQ8ABAEJAAIBAQADAQIAAQERAAEEAQAEAQoABQEQAAUBDAABAQECAQAFAQEAAQEBAgcAAQIEAQEAAQEBBhYAAwEBAAMBCQABAgEBAQAEAQEAAQIPAAEDAQIBAAIBDQADARMABAENAAEEAQAEAQsAAQMBAAQBAQYBAREABAEBAAECAQMIAAUBEAAEAQ4AAQUBAAUBAQABAgEBBgABAQEFAQADAQEAAQQBAxoABAEBAgcAAQUBAQEABQESAAMBDQADAREAAQECAAIBDgABCgEAAwEMAAICAwEDAAECAQEPAAQBAQABAgEDCAAFARAABAERAAUBCgACAQIAAQEBBBkAAQEBAAQBAQIGAAIBAQAFARMAAwENAAMBEQABAQIAAwENAAEJAQADAQ0AAQkFAQEAAQQBAgEDAQQHAAEBAQQCAAQBDQAFARAABAEPAAECAQAGAQEAAQEBAgEAAQEBBAEABgEdAAIBAQACAQEAAQEGAAIDAQABAQEAAwETAAMBDQADARIAAgIBAAIBDQABCgEABAENAAECAgADAQIAAgEIAAEBAQACARAAAQEBAAMBEAADAQEAAgEQAAgBAQABAgEBAQAEAR4ABgEHAAEDBwEQAAECBAENAAMBEgABAgEDAgABAQ0AAQIBAAMBDwABBgIAAQEBAAIBCgAGAQECAQMMAAEBAQABAQEAAQEQAAQBEwAHAQEAAQEBAAQBHwAEAQgAAQEBAwEAAwEBAAEBAgABAQ4AAQQBAgEAAgELAAEFAQADARMAAQUCAAEBDwADAQ8AAQEBBgIAAQEBAA4BAQABAQECDQABAgEBAgACAQ4AAQIBAQMAAQEBAAEEAQEPAAEBAQABAQEACgEhAAMBCQACAQMAAQECAAEDAQQOAAEBDwABAQMAAQETAAEBEAABBQEAAQEBAAEBAQABBQEBDQABAQIAAQUOAAEBAQABAgEEDgABAQIAAQUBAw4AAQICAAEDAQUBAQEAAQETAAkBIwADAQkAAgEBAwEGAQEBAgEFAQMSAAICAQMBAgsAAgEBAwECAQMBARMAAgEOAAEBAQIDAAEFFQABAQIABAIBAQIAAQMBBCQAAQECAAECAQMXAAcBAQABBAEBHwABAQEAAwEJAAEBAgABAgIAAQEVAAEGAQIMAAEEAQcBAAEFAQITAAIDKQABAUgAAgECAAcBAQABAR0AAgICAAMBMwABAY8ACAEBAAECAQQbAAICAQAEAQIAAQXCAAYBAQACAh4ABQHDAAgBAgABAh0ABQHCAAIDAgABAQEABAEBAAEEAQIaAAEBAQIFAcMAAQEBBQECBwEBAAEBGgABAQEDAQAEAQEAAQHCAAEBAQUBAAkBHAAFAQEFxwAGAQEAAQQBAhgAAQIGAcgABgEBAAEEAQIbAAMBAQACAccABQEBAAEBGwAFAcoABQEBAAEDGQACAQEABAHJAAUBAQABBgEEGwACAQEAAQECAAECxgAFARsAAgEBAAUBAQABAccABAEdAAECAQAEAQEAAgHEAAECAQEBAAMBHQACAQEAAQEBAAIBAQACAsMAAQICAAMBAQABBBwAAgEDAAEBAQACAcQAAQgBAAMBAQABBB0AAgICAAIBxgABBAEAAwEBAAEBIgACAQIAAQHEAAEBAgABAQEEIAACAQEAAQEBAAECAQQBAcMAAgEBAAEGAQkgAAEBAQABAQEAAQECAAIBwAABAwEEAQACAQEDIQABAQEEAQEBAAEBAgABBAECwQACAQEAAQIBASEAAQEBAgEDAQQBAAIBxQACAycAAQHDAAEBAQYBBAECBwA=";

static uint8_t logoRle[6404];
static bool logoDecoded = false;

static int8_t b64Value(char c) {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
}

static size_t decodeBase64() {
    if (logoDecoded) return sizeof(logoRle);
    size_t out = 0; int val = 0, bits = -8;
    for (size_t i = 0; i < sizeof(logoEncoded) - 1 && out < sizeof(logoRle); ++i) {
        int8_t v = b64Value(pgm_read_byte(logoEncoded + i));
        if (v < 0) continue;
        val = (val << 6) | v; bits += 6;
        if (bits >= 0) { logoRle[out++] = (uint8_t)((val >> bits) & 0xFF); bits -= 8; }
    }
    logoDecoded = (out == sizeof(logoRle));
    return out;
}

static uint16_t alphaTo565(uint8_t a) {
    uint16_t r = (uint16_t(a) * 31 + 7) / 15;
    uint16_t g = (uint16_t(a) * 63 + 7) / 15;
    uint16_t b = (uint16_t(a) * 31 + 7) / 15;
    return (r << 11) | (g << 5) | b;
}

void logoBegin() { decodeBase64(); }

void drawLogoScaled(TFT_eSPI &tft, int16_t x, int16_t y, int16_t w, int16_t h) {
    if (decodeBase64() != sizeof(logoRle) || w <= 0 || h <= 0 || w > 320) return;
    static uint8_t sourceRow[LOGO_SOURCE_W];
    static uint16_t outRow[320];
    size_t pos = 0, pixels = 0;
    int16_t cachedY = -1;
    for (int16_t oy = 0; oy < h; ++oy) {
        int16_t sourceY = (int32_t(oy) * LOGO_SOURCE_H) / h;
        if (sourceY != cachedY) {
            cachedY = sourceY;
            pos = 0; pixels = 0;
            while (pos + 1 < sizeof(logoRle) && pixels < size_t(sourceY) * LOGO_SOURCE_W) {
                pixels += logoRle[pos++]; pos++;
            }
            int rowX = 0;
            while (pos + 1 < sizeof(logoRle) && rowX < LOGO_SOURCE_W) {
                uint8_t count = logoRle[pos++]; uint8_t level = logoRle[pos++];
                int take = min<int>(count, LOGO_SOURCE_W - rowX);
                memset(sourceRow + rowX, level, take); rowX += take;
            }
        }
        for (int16_t ox = 0; ox < w; ++ox) {
            int16_t sourceX = (int32_t(ox) * LOGO_SOURCE_W) / w;
            outRow[ox] = alphaTo565(sourceRow[sourceX]);
        }
        tft.pushImage(x, y + oy, w, 1, outRow);
    }
}
